info:
  app:
    name: TechSpark Actuator App
    description: This is a Spring Boot application to showcase the Actuator capabilities
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        #        include: [ "health", "info", "metrics", "env", "loggers", "mappings", "threaddump", "startup" ]
        include: "*"
